DROP TABLE IF EXISTS genre_line;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS user_friends;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS ratings;

CREATE TABLE IF NOT EXISTS genres (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS ratings (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(30) UNIQUE
);

CREATE TABLE IF NOT EXISTS films (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(100)   NOT NULL,
    description varchar(200)   NOT NULL,
    release_date date,
    duration INTEGER,
    rating_id INTEGER REFERENCES ratings (id),
    CONSTRAINT valid CHECK (duration > 0 AND name <> '')
);

CREATE TABLE IF NOT EXISTS genre_line (
    --id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (id),
    genre_id INTEGER REFERENCES genres (id)
);

CREATE TABLE IF NOT EXISTS users (
    id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(30) UNIQUE NOT NULL,
    login varchar(20)   NOT NULL,
    name varchar(20),
    birthday date
);

CREATE TABLE IF NOT EXISTS likes (
    --id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    film_id INTEGER REFERENCES films (id),
    user_id INTEGER REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS user_friends (
    --id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INTEGER REFERENCES users (id),
    friend_id INTEGER REFERENCES users (id),
    status varchar(10)   NOT NULL
);


